export EDITOR=nvim
export GOPATH=~/.local/share/.go
export PATH=~/.config/waybar/scripts:"$PATH"
export PATH=~/.local/bin:"$PATH"
export ZDOTDIR=~/.config/zsh
export PYTHON_HISTORY=/dev/null
export PKGS_FILE=~/Projects/dotfiles/content/local-bin/pkgs
