export EDITOR=nvim
export GOPATH=~/.local/share/.go
export PATH=~/.config/waybar/scripts:"$PATH"
export PATH=~/.local/bin:"$PATH"
export ZDOTDIR=~/.config/zsh
export PYTHON_HISTORY=/dev/null
export PKGS_FILE=~/Projects/dotfiles/content/local-bin/pkgs

export THEMES_DIR=~/Projects/dotfiler/content/themes/
export ICONS_DIR=~/Projects/dotfiler/content/icons/
