font_family JetBrainsMono Nerd Font Mono
font_size 12

foreground #C1C1C1
background #000000
selection_background #303030
selection_foreground #FAFAFA
url_color #79b8ff
cursor #FAFAFA
cursor_text_color #000000

active_tab_background #000000
active_tab_foreground #FAFAFA
inactive_tab_background #000000
inactive_tab_foreground #727272

active_border_color #383838
inactive_border_color #000000

color0 #000000
color1 #f97583
color2 #7CB342
color3 #ffab70
color4 #79b8ff
color5 #b392f0
color6 #4db8b8
color7 #C1C1C1

color8 #5c5c5c
color9 #FF7A84
color10 #8BC34A
color11 #FF9800
color12 #79b8ff
color13 #b392f0
color14 #56B4B4
color15 #FAFAFA

clear_all_shortcuts yes
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

map ctrl+shift+equal increase_font_size
map ctrl+shift+minus decrease_font_size
