general {
    hide_cursor = true
}

auth {
    pam {
        enabled = true
    }
}

animations {
    enabled = true
}

background {
    monitor = 
    path = screenshot
    blur_passes = 3
}

input-field {
    monitor = 
    
    size = 290, 45
    outline_thickness = 2
    dots_size = 0.2
    
    outer_color = 0xffD3C6AA
    inner_color = 0xff232A2E 
    
    font_color = 0xffD3C6AA
    font_family = JetBrainsMono Nerd Font Mono
   
    placeholder_text = Password
    
    rounding = 0 
    
    check_color = 0xffDBBC7F
    fail_color = 0xffE67E80
    fail_text = Authentication Failed
    capslock_color = 0xffE69875
    numlock_color = 0xffD3C6AA
    bothlock_color = 0xffE69875

    halign = center
    valign = center
}
